  create TABLE "SSMEHEND"."PATIENT_SYM_MAPPING"
   (	"SID" NUMBER,
	"SYM_CODE" VARCHAR2(20),
	"SEVERITY" VARCHAR2(20),
	"DURATION" NUMBER,
	"REOCCURING" CHAR(1),
	"CAUSE" VARCHAR2(20),
	"PRIORITY" VARCHAR2(20),
	"BP_CODE" VARCHAR2(20),
	 CONSTRAINT "PID" FOREIGN KEY ("SID")
	  REFERENCES "SSMEHEND"."PATIENT_SESSION" ("ID") ENABLE,
	 CONSTRAINT "SC" FOREIGN KEY ("SYM_CODE")
	  REFERENCES "SSMEHEND"."SYMPTOM" ("CODE") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  create TABLE "SSMEHEND"."SERVICEDEPAT_HAS_BODYPART"
   (	"SD_ID" VARCHAR2(20),
	"BP_ID" VARCHAR2(20),
	 CONSTRAINT "SD_CODE" FOREIGN KEY ("SD_ID")
	  REFERENCES "SSMEHEND"."SERVICE_DEPT" ("ID") ENABLE,
	 CONSTRAINT "BP_CODE" FOREIGN KEY ("BP_ID")
	  REFERENCES "SSMEHEND"."BODYPART" ("CODE") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  create TABLE "SSMEHEND"."STAFF_SD"
   (	"EMP_ID" VARCHAR2(20),
	"SD_ID" VARCHAR2(20),
	 CONSTRAINT "EMPID" FOREIGN KEY ("EMP_ID")
	  REFERENCES "SSMEHEND"."STAFF" ("EMPLOYEE_ID") ENABLE,
	 CONSTRAINT "SD" FOREIGN KEY ("SD_ID")
	  REFERENCES "SSMEHEND"."SERVICE_DEPT" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  create TABLE "SSMEHEND"."SEVERITY_SCALE"
   (	"ID" VARCHAR2(20),
	"SCALE" VARCHAR2(20)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  create TABLE "SSMEHEND"."PATIENT"
   (	"PID" NUMBER NOT NULL ENABLE,
	"F_NAME" VARCHAR2(20),
	"L_NAME" VARCHAR2(20),
	"DOB" DATE,
	"PHONE_NUMBER" NUMBER(10,0),
	"ADDRESS_ID" NUMBER,
	 CONSTRAINT "PATIENT_PK" PRIMARY KEY ("PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "ADD_FK" FOREIGN KEY ("ADDRESS_ID")
	  REFERENCES "SSMEHEND"."ADDRESS" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  create TABLE "SSMEHEND"."REPORT"
   (	"PATIENT_ID" NUMBER,
	"REFERRAL_STATUS_ID" VARCHAR2(20),
	"NEGATIVE_EXPERIENCE" CHAR(1),
	"DISCHARGE_STATUS" VARCHAR2(20),
	"TREATMENT_GIVEN" VARCHAR2(20),
	 CONSTRAINT "VALID_NEG" CHECK (negative_experience='y' or negative_experience='n') ENABLE,
	 CONSTRAINT "FK_REPORT" FOREIGN KEY ("PATIENT_ID")
	  REFERENCES "SSMEHEND"."PATIENT_SESSION" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  create TABLE "SSMEHEND"."REFERRAL_STATUS"
   (	"FACILITY_ID" NUMBER,
	"EMPLOYEE_ID" VARCHAR2(20),
	"REASON_CODE" NUMBER,
	 CONSTRAINT "FK_REFERRAL_STATUS" FOREIGN KEY ("FACILITY_ID")
	  REFERENCES "SSMEHEND"."HOSPITAL" ("FACILITY_ID") ENABLE,
	 CONSTRAINT "FK_REFFERAL_STATUS" FOREIGN KEY ("EMPLOYEE_ID")
	  REFERENCES "SSMEHEND"."STAFF" ("EMPLOYEE_ID") ENABLE,
	 CONSTRAINT "FK_REFERRAL_STATU" FOREIGN KEY ("REASON_CODE")
	  REFERENCES "SSMEHEND"."REASON" ("REASON_CODE") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  create TABLE "SSMEHEND"."REASON"
   (	"REASON_CODE" NUMBER NOT NULL ENABLE,
	"SERVICE_NAME" VARCHAR2(20),
	"DESCRIPTION" VARCHAR2(20),
	 CONSTRAINT "REASON_PK" PRIMARY KEY ("REASON_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  create TABLE "SSMEHEND"."SYM_SEVERITY"
   (	"CODE" VARCHAR2(20),
	"SEVERITY" VARCHAR2(20),
	 CONSTRAINT "CODE" FOREIGN KEY ("CODE")
	  REFERENCES "SSMEHEND"."SYMPTOM" ("CODE") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  create TABLE "SSMEHEND"."PATIENT_SESSION"
   (	"ID" NUMBER NOT NULL ENABLE,
	"CHECKIN_START" TIMESTAMP (6),
	"CHECKIN_END" TIMESTAMP (6),
	"TEMPERATURE" NUMBER,
	"BLOOD_PRESSURE_S" NUMBER,
	"BLOOD_PRESSURE_D" NUMBER,
	"FACILITY_ID" NUMBER(*,0),
	"TREATED" CHAR(1),
	"TREATMENT_TIME" TIMESTAMP (6),
	"TREATMENT_DESC" VARCHAR2(20),
	"PID" NUMBER,
	 CONSTRAINT "LOGIN_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "PID_FK" FOREIGN KEY ("PID")
	  REFERENCES "SSMEHEND"."PATIENT" ("PID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  create TABLE "SSMEHEND"."STAFF"
   (	"EMPLOYEE_ID" VARCHAR2(20) NOT NULL ENABLE,
	"HIRE_DATE" DATE,
	"DESIGNATION" VARCHAR2(40),
	"FNAME" VARCHAR2(40),
	"LNAME" VARCHAR2(40),
	"ADDRESS_ID" NUMBER,
	"FACILITY_ID" NUMBER,
	"PHONENUMBER" VARCHAR2(10),
	"DOB" DATE,
	 CONSTRAINT "STAFF_PK" PRIMARY KEY ("EMPLOYEE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "ADDRESS_FK_SYMPTOM" FOREIGN KEY ("ADDRESS_ID")
	  REFERENCES "SSMEHEND"."ADDRESS" ("ID") ENABLE,
	 CONSTRAINT "FACILITY_FK_STAFF" FOREIGN KEY ("FACILITY_ID")
	  REFERENCES "SSMEHEND"."HOSPITAL" ("FACILITY_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  create TABLE "SSMEHEND"."SYMPTOM"
   (	"CODE" VARCHAR2(20) NOT NULL ENABLE,
	"NAME" VARCHAR2(20),
	"BP_CODE" VARCHAR2(20),
	 CONSTRAINT "SYMPTOM_PK" PRIMARY KEY ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "BODYPART" FOREIGN KEY ("BP_CODE")
	  REFERENCES "SSMEHEND"."BODYPART" ("CODE") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  create TABLE "SSMEHEND"."BODYPART"
   (	"CODE" VARCHAR2(20) NOT NULL ENABLE,
	"NAME" VARCHAR2(20),
	 CONSTRAINT "BODYPART_PK" PRIMARY KEY ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  create TABLE "SSMEHEND"."ADDRESS"
   (	"ID" NUMBER NOT NULL ENABLE,
	"CITY" VARCHAR2(20),
	"STREET_NAME" VARCHAR2(40),
	"COUNTRY" VARCHAR2(20),
	"STATE" VARCHAR2(20),
	 CONSTRAINT "ADDRESS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  create TABLE "SSMEHEND"."CERTIFICATION"
   (	"NAME" VARCHAR2(80),
	"ACRONYM" VARCHAR2(20) NOT NULL ENABLE,
	"EXPIRY_DATE" DATE,
	"DATE_CERTIFIED" VARCHAR2(20),
	 CONSTRAINT "CERTIFICATION_PK" PRIMARY KEY ("ACRONYM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  create TABLE "SSMEHEND"."HOSPITAL"
   (	"FACILITY_ID" NUMBER NOT NULL ENABLE,
	"CERT_ACRONYM" VARCHAR2(20),
	"ADDRESS_ID" NUMBER,
	"NAME" VARCHAR2(20),
	"CAPACITY" VARCHAR2(20),
	"NO_SERVICE_DEPARTMENTS" VARCHAR2(20),
	"CLASSIFICATION" NUMBER,
	 CONSTRAINT "HOSPITAL_PK" PRIMARY KEY ("FACILITY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "ADDRESS_FK_HOSPITAL" FOREIGN KEY ("ADDRESS_ID")
	  REFERENCES "SSMEHEND"."ADDRESS" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  create TABLE "SSMEHEND"."ASSESSMENT_RULE"
   (	"ID" NUMBER(*,0) NOT NULL ENABLE,
	"RULES" VARCHAR2(20) NOT NULL ENABLE,
	"PRIORITY" VARCHAR2(20) NOT NULL ENABLE,
	 CONSTRAINT "ASSESSMENT_RULE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  create TABLE "SSMEHEND"."SERVICE_DEPT"
   (	"ID" VARCHAR2(20) NOT NULL DISABLE,
	"TYPE" VARCHAR2(20) NOT NULL DISABLE,
	"NAME" VARCHAR2(20),
	"EMPID" VARCHAR2(20),
	 CONSTRAINT "SERVICE_DEPT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "SERVICE_DEPT_FK1" FOREIGN KEY ("ID")
	  REFERENCES "SSMEHEND"."STAFF" ("EMPLOYEE_ID") DISABLE,
	 CONSTRAINT "EMP_ID" FOREIGN KEY ("EMPID")
	  REFERENCES "SSMEHEND"."STAFF" ("EMPLOYEE_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS";

  create TABLE "SSMEHEND"."SERVICE"
   (	"CODE" VARCHAR2(20) NOT NULL ENABLE,
	"EQUIPMENT" VARCHAR2(40) NOT NULL ENABLE,
	"SERVICE_DEPT_ID" VARCHAR2(20) NOT NULL ENABLE,
	 CONSTRAINT "SERVICE_FK1" FOREIGN KEY ("SERVICE_DEPT_ID")
	  REFERENCES "SSMEHEND"."SERVICE_DEPT" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


--------------------------------------------------TRIGGERS FOR PKs------------------------------------------------------
create sequence address_id_seq;

create or replace trigger address_bi
before insert on address
for each row
begin
  select address_id_seq.nextval
  into :new.ID
  from dual;
end;


create sequence patient_id_seq;

create or replace trigger patient_bi
before insert on patient
for each row
begin
  select patient_id_seq.nextval
  into :new.ID
  from dual;
end;

create sequence patient_session_id_seq;

create or replace trigger patient_session_bi
before insert on PATIENT_SESSION
for each row
begin
  select patient_session_id_seq.nextval
  into :new.ID
  from dual;
end;

create sequence neg_exp_id_seq;

create or replace trigger neg_exp_bi
before insert on NEGATIVE_EXP
for each row
begin
  select neg_exp_id_seq.nextval
  into :new.N_ID
  from dual;
end;

create sequence referral_status_id_seq;

create or replace trigger referral_status_bi
before insert on REFERRAL_STATUS
for each row
begin
  select referral_status_id_seq.nextval
  into :new.ID
  from dual;
end;